### ISSUE TITLE
Testing: Algorithm does not segment foreground

### ISSUE THREAD

**Issue by AjmalShahbaz** [lim-anggun/FgSegNet#10]
Dear Long Ang Lim, 

Thank you for providing your source code with detail guide to run it. 

I successfully trained your method on several CDNet videos. However, when I tried to test it on remaining frames say highway sequence, it does not segment foreground object. The binary mask obtained shows only background values.
I tried every possible solution. All in vain. 
Do you have any idea what going wrong?

Thank You. 
  
![fg](https://user-images.githubusercontent.com/41987885/43509139-bfd9a350-95ac-11e8-8df9-159f76f1fdd0.png)

**Comment by lim-anggun** [comment]
hi @AjmalShahbaz,
Can you give more details please? 

Note that output values from sigmoid function are in the range of [0,1] (you can see only black pixel, by eyes). You need to convert those values to the range of [0, 255] before saving as images. Actually, I use `scipy.misc.imsave()` to save predicted masks as images directly without converting those predicted mask values to the range of [0, 255]. It handles this conversion for me automatically.

You may give it a try with [this provided Jupyter notebook](https://github.com/lim-anggun/FgSegNet/blob/master/test_prediction.ipynb), just replace with your trained model `(mdl_path = 'your_model_name.h5'`). Let me know if it works.

**Comment by AjmalShahbaz** [comment]
Dear Long Ang Lim, 

Thank you for your reply.
I was able to solve the issue.
