### ISSUE TITLE
Unknown layer: MyUpSampling2D

### ISSUE THREAD

**Issue by wu-ruijie** [lim-anggun/FgSegNet#11]
hi :
I run your test_prediction.ipynb, and use my train weight xxx.h5,but I get a error "Unknown layer: MyUpSampling2D" when load_model(mdl_path), do you got this issue ?
thanks vary much

**Comment by lim-anggun** [comment]
hi,
You can fix this error by adding `MyUpSampling2D` object to the `load_model` function.
First, copy `my_upsampling_2d.py` to the same directly as your Jupyter notebook and add the following line to `load_model` function:

```
from my_upsampling_2d import MyUpSampling2D
model = load_model(mdl_path, custom_objects={'MyUpSampling2D': MyUpSampling2D})
```
I've updated the Jupyter notebook, please take a look.
