### ISSUE TITLE
about train and test

### ISSUE THREAD

**Issue by lawpdas** [lim-anggun/FgSegNet#17]
I have trained a model with your code, but it can not segment foreground object.
The acc become 0.8937 and 0.8999 at first two epoch, and it will remain unchanged.
Is this normal?
```
Epoch 55/60
40/40 [==============================] - 3s - loss: 1.7747 - acc: 0.8937 - val_loss: 1.6751 - val_acc: 0.8999
Epoch 56/60
40/40 [==============================] - 2s - loss: 1.7732 - acc: 0.8937 - val_loss: 1.6737 - val_acc: 0.8999
Epoch 57/60
40/40 [==============================] - 2s - loss: 1.7717 - acc: 0.8937 - val_loss: 1.6722 - val_acc: 0.8999
Epoch 58/60
40/40 [==============================] - 2s - loss: 1.7703 - acc: 0.8937 - val_loss: 1.6708 - val_acc: 0.8999
Epoch 59/60
40/40 [==============================] - 2s - loss: 1.7689 - acc: 0.8937 - val_loss: 1.6694 - val_acc: 0.8999
Epoch 60/60
40/40 [==============================] - 2s - loss: 1.7675 - acc: 0.8937 - val_loss: 1.6681 - val_acc: 0.8999
```

**Comment by 124399839** [comment]
I have the same problem. Have you solved it?thanks.
I have trained a model with your code, but it can not segment foreground object.
-------------------------------------\
-------------------------------------\

Training ->>> turbulence / turbulence3
Train on 40 samples, validate on 10 samples
Epoch 1/60
40/40 [==============================] - 30s - loss: 0.7687 - acc: 0.9726 - val_loss: 0.7250 - val_acc: 0.9670
Epoch 2/60
40/40 [==============================] - 12s - loss: 0.5907 - acc: 0.9749 - val_loss: 0.7051 - val_acc: 0.9670
Epoch 3/60
40/40 [==============================] - 12s - loss: 0.5678 - acc: 0.9749 - val_loss: 0.6799 - val_acc: 0.9670
Epoch 4/60
40/40 [==============================] - 12s - loss: 0.5423 - acc: 0.9749 - val_loss: 0.6548 - val_acc: 0.9670
Epoch 5/60
40/40 [==============================] - 12s - loss: 0.5294 - acc: 0.9745 - val_loss: 0.6389 - val_acc: 0.9670
Epoch 6/60
40/40 [==============================] - 12s - loss: 0.5040 - acc: 0.9732 - val_loss: 0.4352 - val_acc: 0.9861
Epoch 7/60
40/40 [==============================] - 12s - loss: 0.2585 - acc: 0.9916 - val_loss: 0.2016 - val_acc: 0.9940
Epoch 8/60
40/40 [==============================] - 12s - loss: 0.1973 - acc: 0.9940 - val_loss: 0.1617 - val_acc: 0.9961
Epoch 9/60
40/40 [==============================] - 11s - loss: 0.1717 - acc: 0.9953 - val_loss: 0.2043 - val_acc: 0.9931
Epoch 10/60
40/40 [==============================] - 12s - loss: 0.1499 - acc: 0.9963 - val_loss: 0.1453 - val_acc: 0.9964
Epoch 11/60
40/40 [==============================] - 12s - loss: 0.1261 - acc: 0.9974 - val_loss: 0.1333 - val_acc: 0.9968
Epoch 12/60
40/40 [==============================] - 12s - loss: 0.1179 - acc: 0.9977 - val_loss: 0.1303 - val_acc: 0.9967
Epoch 13/60
40/40 [==============================] - 12s - loss: 0.1061 - acc: 0.9981 - val_loss: 0.1224 - val_acc: 0.9970
Epoch 14/60
40/40 [==============================] - 12s - loss: 0.1014 - acc: 0.9981 - val_loss: 0.1138 - val_acc: 0.9972
Epoch 15/60
40/40 [==============================] - 11s - loss: 0.0889 - acc: 0.9987 - val_loss: 0.1269 - val_acc: 0.9961
Epoch 16/60
40/40 [==============================] - 12s - loss: 0.0834 - acc: 0.9988 - val_loss: 0.1046 - val_acc: 0.9973
Epoch 17/60
40/40 [==============================] - 12s - loss: 0.0795 - acc: 0.9988 - val_loss: 0.0962 - val_acc: 0.9976
Epoch 18/60
40/40 [==============================] - 11s - loss: 0.0725 - acc: 0.9990 - val_loss: 0.1110 - val_acc: 0.9965
Epoch 19/60
40/40 [==============================] - 11s - loss: 0.0689 - acc: 0.9990 - val_loss: 0.1033 - val_acc: 0.9968
Epoch 20/60
40/40 [==============================] - 12s - loss: 0.0637 - acc: 0.9992 - val_loss: 0.0903 - val_acc: 0.9974
Epoch 21/60
40/40 [==============================] - 11s - loss: 0.0612 - acc: 0.9991 - val_loss: 0.0904 - val_acc: 0.9972
Epoch 22/60
40/40 [==============================] - 12s - loss: 0.0575 - acc: 0.9992 - val_loss: 0.0798 - val_acc: 0.9977
Epoch 23/60
40/40 [==============================] - 11s - loss: 0.0532 - acc: 0.9993 - val_loss: 0.0806 - val_acc: 0.9975
Epoch 24/60
40/40 [==============================] - 12s - loss: 0.0512 - acc: 0.9993 - val_loss: 0.0741 - val_acc: 0.9978
Epoch 25/60
40/40 [==============================] - 11s - loss: 0.0483 - acc: 0.9994 - val_loss: 0.0776 - val_acc: 0.9975
Epoch 26/60
40/40 [==============================] - 11s - loss: 0.0447 - acc: 0.9995 - val_loss: 0.0762 - val_acc: 0.9975
Epoch 27/60
40/40 [==============================] - 12s - loss: 0.0431 - acc: 0.9994 - val_loss: 0.0734 - val_acc: 0.9975
Epoch 28/60
40/40 [==============================] - 12s - loss: 0.0413 - acc: 0.9995 - val_loss: 0.0659 - val_acc: 0.9979
Epoch 29/60
40/40 [==============================] - 11s - loss: 0.0382 - acc: 0.9996 - val_loss: 0.0698 - val_acc: 0.9975
Epoch 30/60

**Comment by 124399839** [comment]
Dear Long Ang Lim,

Thank you for providing your source code with detail guide to run it.

I successfully trained your method on several CDNet videos. However, when I used test_prediction.ipynb test it on remaining frames say highway sequence, it does not segment foreground object. 

The value of probs is very Very small，Order of magnitude of e-5、e-7...

![Capture](https://user-images.githubusercontent.com/12602661/57497575-cc8a6580-730a-11e9-87a2-c08527a1365a.PNG)

I tried every possible solution. All in vain.
Do you have any idea what going wrong?

Thank You.

**Comment by 124399839** [comment]
Dear Long Ang Lim,

Thank you for providing your source code with detail guide to run it.

I can get the same result as you by your code and your model,
But i can not get the right result by your code and trained model by myself.

Detail：
model is from https://drive.google.com/open?id=1KiEChAxuweEZHwqT5HrkTCbSjT9MxwUF
code is test_prediction.ipynb，can get the same result as you。


model is trained your method on several CDNet2014 videos.（data、code and Parameter is your provide）
code is test_prediction.ipynb，can not get the same result as you。
the result of mask show as：
![result](https://user-images.githubusercontent.com/12602661/57504074-94445080-7325-11e9-8167-7d7267f2d1d6.jpg)



I tried every possible solution. All in vain.
Do you have any idea what going wrong?

Thank You.

**Comment by 124399839** [comment]
Hi lawpdas, Have you solved the problem?
@lawpdas

**Comment by Tomingz** [comment]
thanks a lot for your great work, but how to make my own data like the CDnet2014? and how to train it?

**Comment by HuangLian126** [comment]
Thank you for providing your code for backgroung subtraction, and it is very useful !  However, i have some issues about how to run FgSegNet_M_S_CDnet.py.  When i run this code, it will show some error: keras.__version__<'2.2': NameError: name 'keras' is not defined.  But, keras has been installed. I don not know why, can you help me?@lim-anggun @124399839 @lawpdas

**Comment by HuangLian126** [comment]
I have trained the model. However, when I run test_prediction.ipynb,  there is a error: ValueError: Unknown loss function:loss. I don not know why, and can you help me? Thanks!

**Comment by HuangLian126** [comment]
I have solved the issue about loss function error. However, when I start to test, I can not segment proground correctly. I found that other people @124399839 had similar problems with me.

**Comment by richardso21** [comment]
> I have trained the model. However, when I run test_prediction.ipynb, there is a error: ValueError: Unknown loss function:loss. I don not know why, and can you help me? Thanks!

I'm also having this error, how did you manage to solve this issue @HuangLian126 ?

**Comment by lawpdas** [comment]
Sorry, I have not solve this problem. I don't wanna waste my time here.

**Comment by CaoZhonglei** [comment]
how can I extract mask?
