### ISSUE TITLE
Evaluation Mode

### ISSUE THREAD

**Issue by ftlong6666** [lim-anggun/FgSegNet#24]
Hi @lim-anggun thank you for your research in this current field. I have a question. In this FgSegNet, I tried to train it on CDNet dataset and I have this weight model.
![image](https://user-images.githubusercontent.com/56487515/80158222-8b15c780-85fa-11ea-906a-1694c3fd0a21.png)

Soon I realized that the model names is same with video names. Is it means that this method generate different model files (one model one video) for comparison in CDNet dataset? Is it possible to make generalized model where all of video only use 1 model file?, and how about the performance? Suppose I have different video should I must have different model file?

Thank you.

**Comment by lim-anggun** [comment]
hi @ftlong6666,
FgSegNet is a scene-specific method. This means that it performs well for a specific-scene and it also be able to adapt to any changes in the scene such as rain, snow etc. 

You can also pick a number of frames from each scene (video), combine them, and then train as a whole. This give you only one model file. The performance may downgrade a bit.
Hope this gives you a hint.
