### ISSUE TITLE
how many models after trainning cdw_dataset2014

### ISSUE THREAD

**Issue by biyaa** [lim-anggun/FgSegNet#3]
"A common approach for moving objects segmentation in a scene is to perform a background subtraction.Several methods have been proposed in this domain."  
above in your paper,  but I readed your code,  
    for scene in scene_list:
        print ('Training ->>> ' + category + ' / ' + scene)
        
        # training frame path and dataset2014 path
        # '..' up dir 1 level 
        train_dir = os.path.join('..', 'FgSegNet_dataset2014', category, scene + str(num_frames))
        dataset_dir = os.path.join('..', 'CDnet2014_dataset', category, scene)
            
        mdl_path = os.path.join(mdl_dir, 'mdl_' + scene + '.h5')

        results = generateData(train_dir, dataset_dir, scene)
        train(results, scene, mdl_path, log_dir, vgg_weights_path)
I have a question
 how many models after trainning cdw_dataset2014? is it common approach ？

**Comment by zengzhi2015** [comment]
@biyaa Hi, I have carefully debugged the code, and found that the method builds different models for different scenes.

**Comment by lim-anggun** [comment]
@zengzhi2015 is right, it's a scene-specefic method as described in our paper.
