### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by InstantWindy** [lim-anggun/FgSegNet#5]
I read your paper,In your paper. it said that it takes  around 23.7 minutes to train for 50 epochs. Considering a video sequence which has 1700 frames with spatial size of 320x240,with a 200-frame traing ,but when I run your code ,I found it takes more time than 23.7 minutes to train in the CDnet2014_dataset.I don't know why ,I use the more version GPU than yours. you mean you take around 23.7 minutes to train for 50 epochs for a category's  one scene or all categories' all scene  ?
  I have a question ,you said the video sequence with size of 320x240,you mean you resize all video sequences to 320x240?but in the code ,I didn't find you process the picture size.
  Anthor question , after training .I use the training model weights to test the picture , the result is bad ,the predict picture is black . what is the reason? Thank you!

**Comment by lim-anggun** [comment]
Hi,
We use any arbitrary size images for training. In the paper, we just pick 320x240-resolution images to show that our model can train/segment by that speed. If we train with lower resolution images than 320x240, it will take less time to train, and vice versa.

> ... using NVIDIA GTX 970 GPU. Considering a video sequence which has 1700 frames with spatial size of **320x240**, with a **200-frame** training, it takes around **23.7 minutes to train for 50 epochs**.

The blank results may cause by training examples X are not corresponding to ground-truths Y (it may cause by the randomness or `glob.glob()`. You have to make sure if both X and Y are matched or you can sort the file names:

```python
X_list = sorted(X_list)
Y_list = sorted(Y_list)
```
