### ISSUE TITLE
ValueError: Error when checking input: expected ip_scale2 to have shape (None, 157, 322, 3) but got array with shape (50, 158, 323, 3)

### ISSUE THREAD

**Issue by marywu-dev** [lim-anggun/FgSegNet#8]
I have a problem, do you know how to solve it, thank you very much!
Training ->>> turbulence / turbulence2
(50, 315, 645, 3) (50, 158, 323, 3) (50, 79, 162, 3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/apsarapangu/disk6/wuting/FgSegNet/FgSegNet-master/FgSegNet/FgSegNet.py in <module>()
    219 
    220         results = generateData(train_dir, dataset_dir, scene)
--> 221         train(results, scene, mdl_path, log_dir, vgg_weights_path)
    222         del results

/apsarapangu/disk6/wuting/FgSegNet/FgSegNet-master/FgSegNet/FgSegNet.py in train(results, scene, mdl_path, log_dir, vgg_weights_path)
    147     redu = keras.callbacks.ReduceLROnPlateau(monitor='val_loss', factor=reduce_factor, patience=num_patience, verbose=1, mode='auto', epsilon=0.0001, cooldown=0, min_lr=0)
    148     model.fit([results[0], results[1], results[2]], results[3], validation_split=0.2, epochs=epoch, batch_size=batch_size, 
--> 149                        callbacks=[redu, chk, tb], verbose=1, class_weight=results[4], shuffle = True)
    150 
    151     del model, results, tb, chk, redu

/apsarapangu/disk6/wuting/Anaconda3/lib/python3.5/site-packages/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, **kwargs)
   1356             class_weight=class_weight,
   1357             check_batch_axis=False,
-> 1358             batch_size=batch_size)
   1359         # Prepare validation data.
   1360         if validation_data:

/apsarapangu/disk6/wuting/Anaconda3/lib/python3.5/site-packages/keras/engine/training.py in _standardize_user_data(self, x, y, sample_weight, class_weight, check_batch_axis, batch_size)
   1232                                     self._feed_input_shapes,
   1233                                     check_batch_axis=False,
-> 1234                                     exception_prefix='input')
   1235         y = _standardize_input_data(y, self._feed_output_names,
   1236                                     output_shapes,

/apsarapangu/disk6/wuting/Anaconda3/lib/python3.5/site-packages/keras/engine/training.py in _standardize_input_data(data, names, shapes, check_batch_axis, exception_prefix)
    138                             ' to have shape ' + str(shapes[i]) +
    139                             ' but got array with shape ' +
--> 140                             str(array.shape))
    141     return arrays
    142 

ValueError: Error when checking input: expected ip_scale2 to have shape (None, 157, 322, 3) but got array with shape (50, 158, 323, 3)

**Comment by ronva-h** [comment]
Did you change the ceil to floor in the pyramids.py file of Skimage?

**Comment by lim-anggun** [comment]
Hi @Mary2333 ,
My apologizes for the delay response. If you use FgSegNet_M, make sure that you modify the `ceil` function in `pyramids.py`. If you still have any problems, please reopen this issue and let me know.
