### ISSUE TITLE
Use on new video sequence

### ISSUE THREAD

**Issue by ahkarami** [lim-anggun/FgSegNet#9]
Dear @lim-anggun,
How one can apply your implemented method on a new video sequence (_i.e.,_ a new video with, for example 50 first frames of it)? The network must be trained again on the new video sequence?

**Comment by lim-anggun** [comment]
hi @ahkarami, it can be trained with any stationary video sequences. And you can manually config ```FgSegNetModule.py``` in case you use different video sequence.
